accounts/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from .views import SignupPageView

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    # Registration page.
    path('signup/', SignupPageView.as_view(), name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
]

pages/urls.py
"""Defined urls patterns for learing logs."""
from django.urls import path
from . import views



app_name = 'pages'

urlpatterns = [
    # Home page
    path('', views.home_page, name='home'),
    # Page that shows all the topics.
    path('topics/', views.topics, name='topics'),
    # Detai page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic_name'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry.format
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for the editing a new entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),


]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class CustomUser(AbstractUser):
    pass

pages/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """A topic the user is lerning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        """Return a string repersentation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        The Meta class holds the extra information for
        managing a model; here, it allows us to set special attribute
        telling Django to use Entries shen it need to refer to more than 
        one entry. Without this , Django would refer to multiple entries as 
        Entrys. 
        """
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return the string repersentation of the model."""
        return f"{self.text[:50]}..."

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    """
    Extends the UserCreationForm amd specify swapping in our 
    CustomUser model and displaying the field email and username.
    """

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):
    """
    Extends the UserChangeForm and specify swapping in our CustomUser
    model and dispalying email and username.
    """

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

pages/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    """Create forms of the topic model."""
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    """Create forms of the the Entry model."""
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widegts = {'text': forms.Textarea(attrs={'cols':80})}

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm

# Create your views here.
class SignupPageView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

pages/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def home_page(request):
    context = {}
    return render(request, 'home.html', context)

# We apply login_required() as a decorators to the topic() view function by prepending 
# login_required with @ symnol.
@login_required
def topics(request):
    """Shows all the topic."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    """Here in context dictionary we use keys value to access data."""
    return render(request, 'topics.html', context)


@login_required
def topic(request, topic_id):
    """Shows a singhle topic and all its enteries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.form
        form = TopicForm()
    else:
        # Post data submitted ; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect ('pages:topics')

    # Display a blank or invailid form
    context = {'form': form}
    return render(request, 'new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        """No data submmited; create a blank form."""
        form = EntryForm()
    else:
        # Post data submmited; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            # Here we are assigning the topic attribute of Entry mode = topic vairable
            new_entry.save()
            return redirect('pages:topic_name', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # Post data submmited; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pages:topic_name', topic_id=topic.id)

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'edit_entry.html', context)
         

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Learning Log{% endblock title %}</title>
    <link rel="stylesheet" href="{%static 'css/base.css' %}">
</head>

<body>
    <p>
        <a href="{% url 'pages:home' %}">Learning Log</a>
        <a href="{% url 'pages:topics' %}">Topics</a>
        {% if user.is_authenticated %}
            Hello, {{ user.username }}
            <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <a href="{% url 'accounts:signup' %}">Register</a>
            <a href="{% url 'login' %}">Log In</a>
        {% endif %}
    </p>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/edit_entry.html
{% extends '_base.html' %}

{% load static %}

{% block title %}Edit Entry{% endblock title %}

{% block content %}
<p><a href="{% url 'pages:new_entry' topic.id %}">{{ topic }}</a></p>
<p>Edit Entry:</p>

<form action="{% url 'pages:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>
{% endblock content %}

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}
<link rel="stylesheet" href="{%static 'css/base.css' %}">

{% block content %}
<div class="background-image">
    <img src="{% static 'images/background-desk.jpg' %}">
</div>
<p>
    Learning Log helps you keep track of your learning, for any topic
    you're learning about.
</p>
{% endblock content %}

templates/new_entry.html
{% extends '_base.html' %}
 
{% load static %}

{% block title %}New Entry{% endblock title %}

{% block content %}
<p><a href="{% url 'pages:new_entry' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{% url 'pages:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>
</form>
{% endblock content %}

templates/new_topic.html
{% extends '_base.html' %}

{% load static %}

{% block title %}New Topic{% endblock title %}

{% block content %}
<p>Add a New Topic</p>
<form action="{% url 'pages:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p}}
    <!-- Above as_p modifier tells django to render all the form elements is paragraph format.-->
    <button name="submit">Add Topic</button>
</form>
{% endblock content %}

templates/topic.html
{% extends '_base.html' %}

{% load static %}

{% block title %}Topic{% endblock title %}

{% block content %}

<p>Topic: {{topic}} </p>
<p>Entries:</p>
<p>
    <a href="{% url 'pages:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <!-- The above (|) represents a template filter - a function that modifies 
        the value in a template varible.-->
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'pages:edit_entry' entry.id %}">Edit entry</a>
        </p>
    </li>
    {% empty %}
        <li>
            There are no entries for the topic yet.
        </li>
    {% endfor %}
</ul>

{% endblock content %}

templates/topics.html
{% extends '_base.html' %}

{% load static %}

{% block title %}Topics{% endblock title %}

{% block content %}
<h1>
    Topics
</h1>
<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'pages:topic_name' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
    <!-- Here empty tag tell djang what to do when there in no item present.-->
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'pages:new_topic' %}">Add a new topic</a>

{% endblock content %}